### ISSUE TITLE
Add Tests to minread module. 

### ISSUE THREAD

**Issue by akwasiio** [wise4rmgod/ReadTime#3]
Generally, it's good practice to add tests to your library. I could help in this aspect as well by submitting a PR with some tests for your review.

**Comment by wise4rmgod** [comment]
definitely man, go ahead and write the test 👌

**Comment by wise4rmgod** [comment]
I will be happy to review it.

**Comment by akwasiio** [comment]
I am waiting for you to review my first PR.

**Comment by wise4rmgod** [comment]
I have done it
